// Stub effect_defs.h - generated file stub
#ifndef EFFECT_DEFS_H
#define EFFECT_DEFS_H

// This file is normally generated by the decomp build system
// Stubbing for PC port build

typedef struct EffectDef {
    int type;
    const char* name;
} EffectDef;

extern EffectDef effect_defs[];

#endif
