// Stub item_data.inc.c for PC port
#include "common.h"
#include "item.h"

// This file is normally generated by the decomp build system
// Stubbing out for PC port

ItemData item_data[] = {
    {0}, // Placeholder
};

u16 item_data_count = 1;
